mysql:
  dsn: "root:123@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local"

app:
  env: "development"
  consumerbroker: "first.example.com:9092"
  producerbroker: "second.example.com:9092"
  #linetoken: "sdjfnasklJBS8asdnas83rq2mSJKnadfdmGFVJGSHBd3845ulzdmnfvsd"

redis:
  addr: "localhost:6379"

secret:
  key: "helloWorld"
  life_span: 1
